### ISSUE TITLE
Peak demand calculation and plotting 

### ISSUE THREAD

**Issue by reconjohn** [demand-consults/demand_acep#22]
For a month, there are different trends between 1 min and 5 min resolutions 
![image](https://user-images.githubusercontent.com/10944497/56517847-d6caf800-64f2-11e9-8068-1ad37b07230d.png)

Below is the only maximum trend.
![image](https://user-images.githubusercontent.com/10944497/56517921-fc580180-64f2-11e9-96c1-683dd630057b.png)
![image](https://user-images.githubusercontent.com/10944497/56517977-1f82b100-64f3-11e9-8ec3-34558466da66.png)

Average and minimum trend with 1 min and 5 mins resolutions 
![image](https://user-images.githubusercontent.com/10944497/56518018-388b6200-64f3-11e9-8651-5ae5563cd3ec.png)
![image](https://user-images.githubusercontent.com/10944497/56518024-3cb77f80-64f3-11e9-8744-5cd0741604fe.png)

If we calculate the area under the curve, 5 min resolution trend shows larger variance, thus the area like - 5% to + 8% difference as below. 
- Area ratio (5 min resolution/ 1 min resolution) for max trend: 1.0819081623151745
- Area ratio for average trend: 1.0006958438271207
- Area ratio for min trend: 0.955816222170618

The area under the curve for the 15 mins interval, decides the peak demand during the billing cycle and thus the energy cost. Using inappropriate resolution will end up with the wrong demand charge. This will affect the smoothing method which plot reflects the best fit of 15 min average kW load.

**Comment by reconjohn** [comment]
It seems not every minute for the average 15 minutes but 15 minute period in order, not overlapping. If the billing cycle is a month, we just need to know just one max point for the demand charge. In this regard, why do we bother with the minute resolution?  We already have the kWh data. I guess we don't need to plot power (kW) but plot energy (kWh) in hour, day, month, or year resolution rather than minute resolution. 

> Our demand meters measure a demand for every 15 minute period in each month. The meters record the highest 15 minute demand for the month and retain this figure until the meter is reset by our meter reading equipment. Each meter makes over 2,800 readings per month. Remember, we base your bill on the highest 15 minute reading; therefore, whether it occurs only once in the month or 2,800 times, we charge the same billing demand.

https://www.duquesnelight.com/account-billing/understanding-your-bill/business-bill/demand-energy-usage

**Comment by aidowu** [comment]
There is no need to calculate the peak demand. In the dataset, there is measurement for 15 min average in a one minute window for the power consumed. We can plot this data to give us the trend.

**Comment by aidowu** [comment]
I found this article helpful in understanding how demand charges are computed [https://www9.nationalgridus.com/niagaramohawk/non_html/eff_elec-demand.pdf]

**Comment by aidowu** [comment]
I found this article helpful in understanding how demand charges are computed [Demand charges are based on the highest 15-minute average usage recorded on the demand meter within a given month.](https://www9.nationalgridus.com/niagaramohawk/non_html/eff_elec-demand.pdf )

**Comment by reconjohn** [comment]
Thanks for the article. 

Yeah, there is a channel named `SlidingWindowRealPowerDemand3Ph(kW)` is a 15 minute average of one minute windows.  See SW Sub-Interval Length (60s) and SW Sub-Interval Count (15) and its `SlidingWindowRealPowerDemand3Ph` for **Sri antenna** and `SPeak` for **Lower range**. I plotted them, but seems wrong.

**Comment by chintanp** [comment]
@reconjohn What milestone is this task related to?

**Comment by chintanp** [comment]
Latest results of the peak demand calculation etc. are in the [documentation](https://demand-acep.readthedocs.io/en/latest/?badge=latest).
