### ISSUE TITLE
Use selected NetCDF file reader to read files according to meter and measurement type

### ISSUE THREAD

**Issue by aidowu** [demand-consults/demand_acep#23]
Parse NetCDF data in preparation for loading into database

**Comment by aidowu** [comment]
I have written code that:
1.  Loads the "Copy of measured channel xlsx" file and reads the meter name and measurement type
2. Goes through all the folders in the data and extracts .nc files
3. Determines the meter name and the measurement type for each .nc file.
4. Combines all measurements for each meter into a single data dataframe.

I implemented the above for a single day. Eventually, we will want to load the data into a database but I put in in a dataframe for now to test the functionality of the code.

**Comment by aidowu** [comment]
To read the .nc file, I found a package called [xarray](http://xarray.pydata.org/en/stable/index.html) It was easier to use and has more features than the _Netcdfhandler.py_ file.

**Comment by chintanp** [comment]
The NetCDF files are being read in the `extract_data()` function as seen [here](https://github.com/demand-consults/demand_acep/blob/36119932492f545f96e3072118b35e6a9d345e67/demand_acep/demand_acep.py#L22)
