### ISSUE TITLE
formal ACEP repository

### ISSUE THREAD

**Issue by dayne** [demand-consults/demand_acep#27]
Great project and organization!  Thanks for your time today and the great conversation.

We would to see the results of this project efforts, the data and docs in this repo, under ACEP's github organization: github.com/acep-uaf/ also.

We have a couple options to accomplish this:
* **Fork**: Leave this repository as the primary and create an acep-uaf fork
   * We would then ensure that project efforts are merged (via pull requests) to the acep-uaf repo as major efforts are completed & at the final results at end of project.
  * Would want to rename the fork on ACEP side to avoid an awkward name: `acep-uaf/demand_acep` to `acep-uaf/demand_charges` or something like that.
  * Would allow `demand-consults` to maintain the _primary_ repository on GitHub.
* **Migrate**: Create a new acep-uaf hosted repository act as primary going forward.
  * Push current repo to new repo and retire this one
  * We want to migrate the issue tracker stuff too

Either pathway is acceptable. We want to make sure your efforts are properly credited and advertised during and after the project. GitHub makes creating a healthy ecosystem around open source code easy to have multiple homes that stay in sync with each other using Pull Requests.

Let me know what you think. 

Best

**Comment by chintanp** [comment]
@dayne Thanks a lot for helping us with this. Conferring with the team, I think we like the fork option.

**Comment by dayne** [comment]
Sounds good.  

We can pull the trigger on the fork path any time in the project.  I think I'd like to save that for when you feel we have hit a major milestone event and we can use it to trigger a broader announcement for our ACEP team/folks.
