### ISSUE TITLE
Understand GVEA pricing strategy. 

### ISSUE THREAD

**Issue by chintanp** [demand-consults/demand_acep#36]
This can affect the smoothing technique/interval. Find out whether they read data per minute or finer.

**Comment by reconjohn** [comment]
# Data pruning for demand charge analysis 

Let's see the behavior of the data for a day, Jan. 01, 2019, the 3 figures the main variables representing the day as below. 
![image](https://user-images.githubusercontent.com/10944497/57188691-ef0a2200-6eb7-11e9-8f2c-9f7e8984a908.png)

The main concern here is demand charge in terms of the peak demand, which is the main factor deciding the cost reduction. 

## Two options 

Through the conversation with an electrical engineer, there are 2 options to find the demand charge based on: 
> Demand (kW) = Energy consumed in the 15-minute interval (kWh) / 0.25 hours

* Option one: By subtracting energy consumption after 15 minutes, we can get energy consumption in the 15 minute interval, thus demand value. We have cumulative energy data (kWh) in `ENetTot and EDelTot` I tried it with the `EDelTot(kWh)`

* Option two: Summing all the power (kW) for each point, then divide it by the number of points for the 15 minutes interval. We can get the average 15 minutes power (kW). We have `PTot` which shows the power trend for each 140 frequency resolution (**about 7 points each second**). 

I plotted them and compared them as below. 
![image](https://user-images.githubusercontent.com/10944497/57188832-f7635c80-6eb9-11e9-9450-fabf70fe456b.png)
![image](https://user-images.githubusercontent.com/10944497/57188834-06e2a580-6eba-11e9-8abf-be6ea62f1801.png)

## Issues 
Here are two issues. 
* The pattern of the plots between the 1st figure and the 2nd one is different. Ideally, they should be similar. 
* The 2nd figure (which comes from the `PTot`) and the 3rd figure (this is the raw data) show the similar trend but the value is different (one is around 353 kW, the other around 279 kW). 

## Next step
We need to figure out which data is more reliable for the analyses as it seems there are certain abnormalities. After addressing the issues, we can use the power trend of each meters for the whole months and years for the forecasting and the further analysis.

**Comment by reconjohn** [comment]
The reason why there is a sudden reduction on the 15 mins average power (kW) from EDetTot is because there is a sudden increase power consumption during the 1st second. 

![image](https://user-images.githubusercontent.com/10944497/57189083-c89bb500-6ebe-11e9-9fc4-89a54c0a547a.png)

**Comment by chintanp** [comment]
A 15 min chunk maximum power is used for demand charge calculation and some calculations are presented [here](https://demand-acep.readthedocs.io/en/latest/charge_filled.html#benefit-cost-analysis-of-involving-a-virtual-meter) in the documentation.
