### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by chintanp** [demand-consults/demand_acep#4]
The team’s first task will be understand the data and the scope of it. The team will then make plans to deal with the missing data and convert the file format to something readily usable etc. if needed.

**Comment by reconjohn** [comment]
I guess we need to first come up with a trend plot of 15 minutes average kW to investigate when the peak demand occurring during the billing cycle for the 4 meters and match all 4 meters for load leveling opportunity if any.

`trends` XL file which has the kW data in a minute resolution and `Power_energy` XL file for the kWh data in 5 minutes resolution
![image](https://user-images.githubusercontent.com/10944497/56261462-f051e700-608f-11e9-8d65-c392469dd385.png)

And this trend is in 7 seconds. 
![image](https://user-images.githubusercontent.com/10944497/56261472-fc3da900-608f-11e9-96a6-748729b26ac2.png)

For the average 15 minutes power (kW) trend plot, which is area below of kW plot for 15 mins / 0.25,
but if we refer to the 1 minute-resolution for the calculation, then the area would be wrong as the area under the second-resolution would be different from the area under the minute-resolution of the power (kW). 

We need to check if there is an area difference between the two cases, if not, we may use the 1 minute-resolution for the mean 15 minutes power (kW) trend plot per each minute point.

**Comment by chintanp** [comment]
Closing as no real task of cleaning here.
