### ISSUE TITLE
Data management plan

### ISSUE THREAD

**Issue by chintanp** [demand-consults/demand_acep#5]
The team will work with ACEP to create a data management plan for future data collection. This could include a data pipeline to streamline the collection of data from multiple sources and transforming it to make it readily usable for analysis.

**Comment by dayne** [comment]
Let me know where/when to review this plan.  

You are generating all sorts of interesting derived datasets we'll want to make sure are captured in addition to the code and documentation you are tracking here in this repository.

**Comment by chintanp** [comment]
@dayne This issue is related to the old usecases document. After talking with Heike we found that ACEP already has a data management plan in place. So we reformatted the usecases document, which now lives on github too here: https://github.com/demand-consults/demand_acep/blob/master/doc/usecases.md. Please feel free to comment on that. The issues were not updated to reflect the current plan. Doing that now, so closing this.
